version: '3.8'

services:
  app:
    build: .
    container_name: ticket-assignment
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - sqlite_data:/app/prisma
    environment:
      DATABASE_URL: "file:/app/prisma/dev.db"
      PORT: 3000
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: sqlite-db
    volumes:
      - sqlite_data:/root/db

volumes:
  sqlite_data:
